
matrix:
 include:
  - os: linux
    dist: xenial
    python: "2.7"
  - os: linux
    dist: xenial
    python: "3.7"

language: python


before_install:
 # Ensures we have a recent python3 
 # https://docs.python-guide.org/starting/install3/osx/
 #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python ; fi
 # Currently there is an issue with 1.16 and SCS; this installs a custom version
 # https://stackoverflow.com/a/48185032
 - pip install -U --only-binary=numpy, scipy numpy==1.15.4
# dask.distributed dropped support for python2 so we need to install the last compatabile version
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] ; then pip install -U distributed==1.28.1 ; fi 
 - docker pull jeffreyhokanson/oas:v1
 - docker pull jeffreyhokanson/multif:v25
 - docker pull jeffreyhokanson/naca0012

install:
 - pip install pytest pycosat
 - python setup.py install 

script:
 - pip freeze --local 
 - pytest tests/


