
matrix:
 include:
  - os: linux
    dist: xenial
    python: "2.7"
  - os: linux
    dist: xenial
    python: "3.4"
  - os: linux
    dist: xenial
    python: "3.5"
  - os: linux
    dist: xenial
    python: "3.6"
  - os: linux
    dist: xenial
    python: "3.7"
#  - os: osx
#    env: PYTHON=2.7
#  - os: osx
#    env: PYTHON=3.7
    

language: python

#https://github.com/pybind/python_example/blob/master/.travis.yml
#before_install:
#- |
#  if [ -n "$PYTHON" ]; then
#    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#      export PATH="/Users/travis/Library/Python/2.7/bin:$PATH"
#      if [ "${PYTHON:0:1}" = "3" ]; then
#        brew update; brew install python3;
#      fi
#    fi
#  fi

install:
 - pip install pytest pybind11 
 - python setup.py install 

script:
 - pip freeze --local 
 - pytest tests/


