
matrix:
 include:
  - os: linux
    dist: xenial
    python: "2.7"
  - os: linux
    dist: xenial
    python: "3.7"
  - os: osx
    python: "2.7"
  - os: osx
    python: "3.7"
  - os: windows
    python: "2.7"
  - os: windows
    python: "3.7"
    

language: python

install:
 - pip install pytest pybind11 
 - python setup.py install 

script:
 - pip freeze --local 
 - pytest tests/


